apiVersion: v1
kind: Pod
metadata:
  name: envpod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: Variable1
      value: "somevalue"
    - name: Variable2
      value: "someothervalue"
